### ISSUE TITLE
RELEASE_STORE_FILE problem

### ISSUE THREAD

**Issue by azizsan** [bornander/lala#1]
Error:Could not get unknown property 'RELEASE_STORE_FILE' for SigningConfig_Decorated{name=release, storeFile=null, storePassword=null, keyAlias=null, keyPassword=null, storeType=null, v1SigningEnabled=true, v2SigningEnabled=true} of type com.android.build.gradle.internal.dsl.SigningConfig.

could you help me solve this problem

**Comment by bornander** [comment]
`RELEASE_STORE_FILE` is a property defined in my *gradle.properties* file in my *user home* directory (https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties), it holds the path to the key store file used to sign the project. If you don't want to define it like that you can replace it with the path to your key store.

I'll add a comment in the Gradle file about this.

**Comment by bornander** [comment]
Added comment to the android/gradle.properties file.
